"""
=====================================================================
OSMOSIS STEM FORMULA ENRICHMENT PIPELINE - SECTION A (BATCH 2)
=====================================================================
Enriches mathematical, physical, and chemical formulas for Section A
(Items 71-110) using KaTeX LaTeX typesetting.
"""

import json
import os
import sys

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

sys.path.insert(0, os.path.dirname(__file__))
import clean_and_enrich_formulas as cleaner

BATCH_A2_DEFINITIONS = {
    "aitken's method": (
        "A numerical acceleration technique (also called Aitken's $\\Delta^2$ process) used to accelerate the rate of convergence "
        "of a sequence generated by an iterative fixed-point iteration $x_{n+1} = f(x_n)$. Given three consecutive approximations "
        "$x_n, x_{n+1}, x_{n+2}$, the accelerated estimate is calculated as: "
        "$$x'_n = x_n - \\frac{(x_{n+1} - x_n)^2}{x_{n+2} - 2x_{n+1} + x_n} = \\frac{x_n x_{n+2} - x_{n+1}^2}{x_{n+2} - 2x_{n+1} + x_n}$$"
    ),
    "aldaric acids": (
        "Polyhydroxy dicarboxylic acids having the general formula: "
        "$$\\text{HOOC}-(\\text{CHOH})_n-\\text{COOH} \\quad \\text{or} \\quad \\text{HOC}(=\\text{O})[\\text{CH}(\\text{OH})]_n\\text{C}(=\\text{O})\\text{OH}$$ "
        "They are formed by the oxidation of both terminal carbon groups (the aldehyde and primary alcohol groups) of an aldose to carboxyl groups."
    ),
    "aldehydes": (
        "A class of organic chemical compounds containing a carbonyl group bonded to at least one hydrogen atom, with the general formula: "
        "$$\\text{R}-\\text{CHO} \\quad \\text{or} \\quad \\text{RC}(=\\text{O})\\text{H}$$ "
        "where $\\text{R}$ is a hydrogen atom or an alkyl/aryl hydrocarbon radical. Aldehydes are formed by the oxidation of primary alcohols: "
        "$$\\text{R}-\\text{CH}_2\\text{OH} \\xrightarrow{[\\text{O}]} \\text{R}-\\text{CHO} \\xrightarrow{[\\text{O}]} \\text{R}-\\text{COOH}$$ "
        "Common examples include methanal (formaldehyde, $\\text{HCHO}$) and ethanal (acetaldehyde, $\\text{CH}_3\\text{CHO}$)."
    ),
    "aldonic acids": (
        "Polyhydroxy monocarboxylic acids with the general formula: "
        "$$\\text{HOCH}_2-(\\text{CHOH})_n-\\text{COOH} \\quad \\text{or} \\quad \\text{HOCH}_2[\\text{CH}(\\text{OH})]_n\\text{C}(=\\text{O})\\text{OH}$$ "
        "Derived from an aldose by the mild oxidation of the terminal aldehyde group ($-\\text{CHO}$) to a carboxyl group ($-\\text{COOH}$), such as D-gluconic acid."
    ),
    "aleph": (
        "In set theory, the sequence of transfinite cardinal numbers used to represent the cardinality of infinite sets, denoted by the Hebrew letter $\\aleph$ (aleph). "
        "$\\aleph_0$ (aleph-null or aleph-nought) is the smallest infinite cardinal, representing the cardinality of the set of natural numbers $\\mathbb{N}$ (countably infinite sets). "
        "$\\aleph_1$ (aleph-one) is the cardinality of the set of all countable ordinal numbers, representing an uncountable set. "
        "By Cantor's Continuum Hypothesis: "
        "$$2^{\\aleph_0} = \\aleph_1$$"
    ),
    "algebra": (
        "1. A fundamental branch of mathematics in which symbols (typically letters such as $x, y, z$) represent numbers or quantities in equations and formulas, "
        "expressing universal arithmetic relationships such as the commutative property: "
        "$$x + y = y + x \\quad \\text{and} \\quad xy = yx$$ "
        "2. Abstract algebra investigates algebraic structures including groups, rings, fields, and vector spaces. "
        "3. Boolean algebra formalises logic operations where variables take values in $\{0, 1\}$."
    ),
    "algebra of sets": (
        "The systematic mathematical framework and laws governing set operations of union ($\\cup$), intersection ($\\cap$), and complementation ($'$). "
        "Key set-theoretic laws include: "
        "$$\\text{Commutative: } A \\cup B = B \\cup A, \\quad A \\cap B = B \\cap A$$ "
        "$$\\text{Associative: } (A \\cup B) \\cup C = A \\cup (B \\cup C), \\quad (A \\cap B) \\cap C = A \\cap (B \\cap C)$$ "
        "$$\\text{Distributive: } A \\cup (B \\cap C) = (A \\cup B) \\cap (A \\cup C), \\quad A \\cap (B \\cup C) = (A \\cap B) \\cup (A \\cap C)$$ "
        "$$\\text{De Morgan's Laws: } (A \\cup B)' = A' \\cap B', \\quad (A \\cap B)' = A' \\cup B'$$"
    ),
    "algebraic addition theorem": (
        "1. Any relation expressing a function of a sum $f(x + y)$ in terms of algebraic combinations of $f(x)$ and $f(y)$ through a polynomial relation: "
        "$$P(f(x), f(y), f(x + y)) = 0$$ "
        "For example, the exponential function satisfies the addition theorem: "
        "$$\\exp(x + y) = \\exp(x) \\cdot \\exp(y)$$ "
        "2. In elliptic function theory, Abel's theorem proves that every elliptic function satisfies an algebraic addition theorem."
    ),
    "algebraic curve": (
        "A curve in the coordinate plane whose points $(x, y)$ satisfy a polynomial equation: "
        "$$P(x, y) = 0$$ "
        "where $P(x, y)$ is a polynomial with real or complex coefficients. Algebraic curves are classified by their degree: "
        "degree 1 curves are straight lines ($ax + by + c = 0$); degree 2 curves are conic sections (circle $x^2 + y^2 = r^2$, ellipse $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1$, parabola $y = ax^2 + bx + c$, hyperbola); "
        "degree 3 curves are cubic curves; and degree 4 curves are quartic curves."
    ),
    "algebraic equation": (
        "A mathematical equation formed by setting a polynomial equal to zero: "
        "$$P(x) = a_n x^n + a_{n-1} x^{n-1} + \\dots + a_1 x + a_0 = 0$$ "
        "where $a_n \\neq 0$ and exponents are non-negative integers. "
        "By the Fundamental Theorem of Algebra, any non-zero polynomial equation of degree $n$ with complex coefficients has exactly $n$ complex roots (counted with multiplicity)."
    ),
    "algebraic expression": (
        "A mathematical phrase combining numbers, variables, and arithmetic operations (addition, subtraction, multiplication, division, and exponentiation), such as: "
        "$$5x^3 - 3y^2 + 2xy$$ "
        "Classified by the number of terms: a monomial has one term ($3a$), a binomial has two terms ($4x + 3y$), a trinomial has three terms ($2x^2 - 3x + 1$), "
        "and expressions with more terms are polynomials."
    ),
    "algebraic function": (
        "A function $y = f(x)$ that satisfies a polynomial equation whose coefficients are themselves polynomials in $x$: "
        "$$p_n(x) y^n + p_{n-1}(x) y^{n-1} + \\dots + p_1(x) y + p_0(x) = 0$$ "
        "Algebraic functions are constructed using a finite number of basic algebraic operations ($+, -, \\times, \\div$) and root extractions ($n$-th roots). "
        "Functions that cannot be expressed this way (such as $\\sin x, \\cos x, e^x, \\ln x$) are transcendental functions."
    ),
    "algebraic integer": (
        "A complex number $\\alpha$ that is a root of a monic polynomial with integer coefficients: "
        "$$x^n + a_{n-1} x^{n-1} + \\dots + a_1 x + a_0 = 0 \\quad (a_i \\in \\mathbb{Z})$$ "
        "For example, $\\sqrt{2}$ is an algebraic integer because it satisfies $x^2 - 2 = 0$. "
        "The set of all algebraic integers forms an integral domain, closed under addition, subtraction, and multiplication."
    ),
    "algebraic number": (
        "A real or complex number that is a root of a non-zero polynomial in one variable with rational (or integer) coefficients: "
        "$$a_n x^n + a_{n-1} x^{n-1} + \\dots + a_1 x + a_0 = 0 \\quad (a_i \\in \\mathbb{Q}, a_n \\neq 0)$$ "
        "For example, $\\sqrt{2}$ and the golden ratio $\\phi = \\frac{1 + \\sqrt{5}}{2}$ are algebraic numbers. "
        "Numbers that are not algebraic, such as $\\pi$ and $e$, are transcendental numbers."
    ),
    "algebraic sum": (
        "The resultant sum obtained by adding a set of quantities while taking their respective positive ($+$) and negative ($-$) signs into account: "
        "$$\\sum_{i=1}^n x_i = x_1 + x_2 + \\dots + x_n$$ "
        "For example, the algebraic sum of $-2, 8$ and $-1$ is $(-2) + 8 + (-1) = 5$."
    ),
    "allometric growth": (
        "The differential growth rate of different organs or parts of an organism in relation to the growth of the whole body, modeled by Huxley's allometric equation: "
        "$$Y = b X^\\alpha \\quad \\text{or in logarithmic form} \\quad \\log Y = \\log b + \\alpha \\log X$$ "
        "where $Y$ is the size or mass of the organ, $X$ is the size or mass of the organism, $\\alpha$ is the allometric growth coefficient, and $b$ is a proportionality constant. "
        "When $\\alpha = 1$, growth is isometric; when $\\alpha > 1$, it is positive allometry; and when $\\alpha < 1$, it is negative allometry."
    ),
    "almost perfect number": (
        "A natural number $n$ such that the sum of its proper divisors equals $n - 1$, or equivalently the sum-of-divisors function satisfies: "
        "$$\\sigma(n) = 2n - 1$$ "
        "All known almost perfect numbers are powers of 2 ($2^k$ for $k \\ge 0$): $1, 2, 4, 8, 16, 32, \\dots$, since: "
        "$$\\sum_{i=0}^{k-1} 2^i = 2^k - 1$$"
    ),
    "alpha decay": (
        "A type of radioactive decay in which an unstable atomic nucleus spontaneously disintegrates by emitting an alpha particle ($\\alpha$, a helium-4 nucleus, ${}_2^4\\text{He}$). "
        "The nuclear decay equation is: "
        "$${}_Z^A\\text{X} \\longrightarrow {}_{Z-2}^{A-4}\\text{Y} + {}_2^4\\text{He}$$ "
        "where $\\text{X}$ is the parent nuclide, $\\text{Y}$ is the daughter nuclide, $A$ is the mass number, and $Z$ is the atomic number. "
        "The atomic number decreases by 2 and the mass number decreases by 4. Common in heavy radioisotopes such as uranium and radium."
    ),
    "alternate angles": (
        "Pairs of non-adjacent interior angles situated on opposite sides of a transversal line intersecting two coplanar lines. "
        "If the two intersected lines are parallel, the alternate interior angles are equal: "
        "$$\\angle a = \\angle b$$"
    ),
    "alternating current": (
        "An electric current that periodically reverses its direction of flow and continuously changes its magnitude with time. "
        "For a standard sinusoidal alternating current (AC) and voltage: "
        "$$I(t) = I_0 \\sin(\\omega t) = I_0 \\sin(2\\pi f t)$$ "
        "$$V(t) = V_0 \\sin(\\omega t) = V_0 \\sin(2\\pi f t)$$ "
        "where $I_0$ and $V_0$ are peak current and voltage, $\\omega = 2\\pi f = \\frac{2\\pi}{T}$ is angular frequency, $f$ is frequency in Hertz (Hz), and $T$ is period. "
        "The root-mean-square (RMS) effective values are: "
        "$$I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}} \\approx 0.707 I_0 \\quad \\text{and} \\quad V_{\\text{rms}} = \\frac{V_0}{\\sqrt{2}} \\approx 0.707 V_0$$"
    ),
    "alternating series test": (
        "Leibniz's criterion for testing the convergence of an alternating series $\\sum_{n=1}^{\\infty} (-1)^{n-1} b_n$ (where $b_n > 0$). "
        "The series converges if: "
        "1. The terms decrease monotonically: $b_{n+1} \\le b_n$ for all $n$. "
        "2. The limit of the terms is zero: $\\lim_{n \\to \\infty} b_n = 0$. "
        "A classic example is the alternating harmonic series: "
        "$$\\sum_{n=1}^{\\infty} \\frac{(-1)^{n-1}}{n} = 1 - \\frac{1}{2} + \\frac{1}{3} - \\frac{1}{4} + \\dots = \\ln 2$$ "
        "and the Gregory-Leibniz series for $\\pi$: "
        "$$1 - \\frac{1}{3} + \\frac{1}{5} - \\frac{1}{7} + \\dots = \\frac{\\pi}{4}$$"
    )
}

def apply_enrichment():
    dict_file = 'dictionary.json'
    print(f"Loading {dict_file}...")
    with open(dict_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0
    a_entries = data.get('A', [])
    word_map = {item.get('word', '').strip().lower(): item for item in a_entries}

    for target_word, new_def in BATCH_A2_DEFINITIONS.items():
        key = target_word.lower()
        if key in word_map:
            word_map[key]['definition'] = new_def
            updated_count += 1
            print(f"  ✓ Updated: [{target_word}]")
        else:
            print(f"  ⚠️ Not found in Section A: [{target_word}]")

    print(f"\nEnriched {updated_count} / {len(BATCH_A2_DEFINITIONS)} definitions in Section A.")

    print(f"Writing updated {dict_file}...")
    with open(dict_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    # Rebuild core_dictionary.js
    cleaner.process_dictionary('dictionary.json', 'dictionary.json', 'core_dictionary.js')
    print("\n✅ Successfully updated dictionary.json and rebuilt core_dictionary.js!")

if __name__ == '__main__':
    apply_enrichment()
